export const HIDE_UPLOAD = "HIDE_UPLOAD";
export const SHOW_UPLOAD = "SHOW_UPLOAD";
export const DISPLAY_UPDATE = "DISPLAY_UPDATE";
export const DISPLAY_DELETE = "DISPLAY_DELETE";
export const RELOAD_HOME = "RELOAD_HOME";
export const HIDE_ALL_MODALS = "HIDE_ALL_MODALS";
